version: '3'

services:
  nodejs-server:
    build: ./nodejs-server
    container_name: nodejs-server
    hostname: volchunovich
    restart: always
    ports:
      - 8080:8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - nodejs-server
