version: '3.7'

services:
  nodejs-server:
    image: ghcr.io/volchunovich/docker-test-app:latest
    container_name: nodejs-server
    pull_policy: always
    hostname: volchunovich
    restart: always
    ports:
      - 8080:8080

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - 80:80
    depends_on:
      - nodejs-server
