name: Build and release Docker image

on:
  push:
    tags:
      - 'v*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: type=semver,pattern={{raw}}

      - name: Build and push nodejs-server
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./nodejs-server
          file: ./nodejs-server/Dockerfile
          push: true
          # platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Save SECRET_KEY to file
        run: echo "${{ secrets.GOOGLE_CLOUD_SECRET_KEY }}" > rsa_key && chmod 600 rsa_key
      - name: Copy nginx config to server
        run: scp -i rsa_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./nginx/default.conf artemvolchunovich@${{ secrets.EXTERNAL_IP_ADDRESS }}:nginx/default.conf
      - name: Copy docker-compose.yml to server
        run: scp -i rsa_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ./docker-compose.yml artemvolchunovich@${{ secrets.EXTERNAL_IP_ADDRESS }}:docker-compose.yml
      - name: Pull and run Docker image
        run: ssh -i rsa_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null artemvolchunovich@${{ secrets.EXTERNAL_IP_ADDRESS }} 'docker-compose up -d'
